#-*- mode: python -*-

listinc=[
      GetLaunchDir(),
      '../../../',
      '/usr/local/include',
      '/usr/include/',
      '/usr/include/python2.5',
      '/usr/local/include/python2.5',
      '/usr/local/include/libxml2',
      '/usr/include/libxml2',
      '.'
      ]

env = Environment(CPPPATH=listinc)

conf = Configure(env, config_h="config.h")

if conf.CheckHeader("Python.h") and conf.CheckLib("python2.5"):
    conf.Define('PYTHON', 1)

conf.CheckLib("util")
conf.CheckLib("pthread")
conf.CheckLib("dl")

env = conf.Finish()

env.SharedLibrary(GetLaunchDir() + "/binaries/plugins/executors/python", ["python.cpp"], SHLIBPREFIX="")
