#-*- mode: python -*-
Import('dest_dir','listinc')

local_listinc=[
      GetLaunchDir(),
      '../../../',
      '/usr/local/include',
      '/usr/include/',
      '/usr/include/guile',
      '/usr/local/include/guile',
      '/usr/local/include/libxml2',
      '/usr/include/libxml2',
      '.'
      ]

local_listinc.extend(listinc)

env = Environment(CPPPATH=local_listinc)

conf = Configure(env, config_h="config.h")

if not conf.CheckHeader("libguile.h") or not conf.CheckLib("guile"):
    print "unable to find lib guile"
    Exit(1)

env = conf.Finish()

env.SharedLibrary(GetLaunchDir() + "/" + dest_dir + "/guile_conf", ["guile_conf.cpp" ], SHLIBPREFIX="")


