#-*- mode: python -*-
Import('dest_dir','listinc')

local_listinc=[
      GetLaunchDir(),
      '../../../',
      '/usr/local/include',
      '/usr/include/',
      '/usr/local/include/libxml2',
      '/usr/include/libxml2',
      '.'
      ]

local_listinc.extend(listinc)

env = Environment(CPPPATH=local_listinc)

conf = Configure(env, config_h="config.h")

if not conf.CheckFunc("php5"):
    print "PHP5 needed!"
    Exit(1)

if not conf.CheckFunc("resolv"):
    print "libresolv needed!"
    Exit(1)

if not conf.CheckFunc("crypt"):
    print "libcrypt needed!"
    Exit(1)


env = conf.Finish()

env.SharedLibrary(GetLaunchDir() + "/" + dest_dir + "/php", ["php.cpp"], SHLIBPREFIX="")

Command(GetLaunchDir() + "/" + dest_dir + "/README","README", Copy("$TARGET", "$SOURCE"))

