\input texinfo
@setfilename myserver

@settitle GNU MyServer Manual

@setchapternewpage odd

@copying
This is the manual for GNU MyServer.

Copyright @copyright{} 2008 Free Software Foundation, Inc.

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.2 or
any later version published by the Free Software Foundation; with the
Invariant Sections being ``The GNU Manifesto,'' ``Distribution'' and
``GNU GENERAL PUBLIC LICENSE,'' with the Front-Cover texts being ``A GNU
Manual,'' and with the Back-Cover Texts as in (a) below.  A copy of the
license is included in the section entitled ``GNU Free Documentation
License.''

(a) The FSF's Back-Cover Text is: ``You have the freedom to copy and
modify this GNU manual.  Buying copies from the FSF supports it in
developing GNU and promoting software freedom.''
@end quotation
@end copying

@dircategory MyServer
@direntry
* MyServer: (myserver).	GNU MyServer.
@end direntry

@tex
\global\hbadness=100000
@end tex

@titlepage
@sp 10
@center @titlefont{GNU MyServer}

@page
@vskip 0pt plus 1filll
Copyright @copyright{} 2008 Free Software Foundation, Inc.
@end titlepage

@iftex
@summarycontents
@contents
@end iftex

@ifnottex
@node Top, Copying, (dir), (dir)
@top GNU MyServer
GNU MyServer is a powerful web server designed, to be easily executed
on a personal computer by the average computer user.
It is based on multi-threaded architecture, which makes it extremely
scalable and usable in large scale sites, as well as in small
networks.  It has built-in supports for the HTTP, HTTPS and FTP
protocols.
Support for dynamic pages is made available trough CGI, ISAPI, WinCGI,
SCGI and FastCGI protocols.
@end ifnottex

@menu
* Copying:: The GNU General Public License gives you permission to
            redistribute GNU MyServer on certain terms; it also explains that
            there is no warranty.
* GNU Free Documentation License:: The license for this documentation.
* Basic configuration:: Basic server configuration.
* Virtual hosts:: Virtual hosts configuration.
* MIME types:: MIME types configuration.
* Process security:: Process security.
* Security files:: Describe how use security files.
* SSL certificates:: Show how to use SSL certificates.
* Log management:: Describe how to use the log management features.

* Concept Index::       An item for each concept.
@end menu

@node Copying, GNU Free Documentation License, Top, Top
@appendix GNU GENERAL PUBLIC LICENSE
@include gpl.texi

@node GNU Free Documentation License, Basic configuration, Copying, Top
@appendix GNU Free Documentation License
@include doclicense.texi

@node Basic configuration, Virtual hosts, GNU Free Documentation License, Top
@chapter Basic configuration
@cindex Basic configuration
@include basic_configuration.texi

@node Virtual hosts, MIME types, Basic configuration, Top
@chapter Virtual hosts
@cindex Virtual hosts
@include virtual_hosts.texi

@node MIME types, Process security, Virtual hosts, Top
@chapter MIME types
@cindex MIME types
@include mime_types.texi

@node Process security, Security files, MIME types, Top
@chapter Process security
@cindex Process security
@include process_security.texi

@node Security files, SSL certificates, Process security, Top
@chapter Process security
@cindex Process security
@include security.texi

@node SSL certificates, Log management, Security files, Top
@chapter SSL certificates
@cindex SSL certificates
@include ssl_certificates.texi

@node Log management, Concept Index, SSL certificates, Top
@chapter Log management
@cindex Log Management
@include log_management.texi

@node Concept Index, , Log management, Top
@unnumbered Concept Index
@printindex cp

@bye
@c -*-texinfo-*-
