\input texinfo
@setfilename myserver.info
@settitle GNU MyServer documentation

@setchapternewpage odd

@titlepage
@sp 10
@center @titlefont{GNU MyServer}

@page
@vskip 0pt plus 1filll
Copyright @copyright{} 2008 Free Software Foundation, Inc.
@end titlepage

@node Top, Copying, (dir), (dir)

This is the manual for the GNU MyServer web server.

@menu
* Copying:: The GNU General Public License gives you permission to
            redistribute GNU MyServer on certain terms; it also explains that
            there is no warranty.
* GNU Free Documentation License:: The license for this documentation.
* General description:: GNU MyServer general description.
* Basic configuration:: Basic server configuration.
* Virtual hosts:: Virtual hosts configuration.
* MIME types:: MIME types configuration.
* Process security:: Process security.
* SSL certificates:: Show how to use SSL certificates.
@end menu


@node Copying, GNU Free Documentation License, Top, Top
@appendix GNU GENERAL PUBLIC LICENSE
@include gpl.texi

@node GNU Free Documentation License, General description, Copying, Top
@appendix GNU Free Documentation License
@include doclicense.texi

@node General description, Basic configuration, GNU Free Documentation License, Top
@chapter General description
@cindex General description
@include general_description.texi

@node Basic configuration, Virtual hosts, General description, Top
@chapter Basic configuration
@cindex Basic configuration
@include basic_configuration.texi

@node Virtual hosts, MIME types, Basic configuration, Top
@chapter Virtual hosts
@cindex Virtual hosts
@include virtual_hosts.texi

@node MIME types, Process security, Virtual hosts, Top
@chapter MIME types
@cindex MIME types
@include mime_types.texi

@node Process security, SSL certificates, MIME types, Top
@chapter Process security
@cindex Process security
@include process_security.texi

@node SSL certificates, , Process security, Top
@chapter SSL certificates
@cindex SSL certificates
@include ssl_certificates.texi


@printindex cp
@contents
@bye
@c -*-texinfo-*-
