#-*- mode: python -*-

Import('dest_dir','listinc')

local_listinc=[
      '/usr/include/python2.5',
      '/usr/local/include/python2.5',
      '/usr/local/include/libxml2',
      '/usr/include/libxml2',
      '.'
      ]

local_listinc.extend(listinc)

env = Environment(CPPPATH=local_listinc)

conf = Configure(env, config_h="config.h")

if conf.CheckHeader("Python.h") and conf.CheckLib("python2.5"):
    conf.Define('PYTHON', 1)

conf.CheckLib("util")
conf.CheckLib("pthread")
conf.CheckLib("dl")

env = conf.Finish()

env.SharedLibrary(GetLaunchDir() + "/" + dest_dir + "/python", ["python.cpp"], SHLIBPREFIX="")

