#-*- mode: python -*-
Import('dest_dir','listinc')

local_listinc=[
      GetLaunchDir(),
      '../../../',
      '/usr/local/include',
      '/usr/include/',
      '/usr/include/guile',
      '/usr/local/include/guile',
      '/usr/local/include/libxml2',
      '/usr/include/libxml2',
      '.'
      ]

local_listinc.extend(listinc)

env = Environment(CPPPATH=local_listinc)

conf = Configure(env, config_h="config.h")

if conf.CheckHeader("libguile.h") and conf.CheckLib("guile"):
    conf.Define('GUILE', 1)

env = conf.Finish()

env.SharedLibrary(GetLaunchDir() + "/" + dest_dir + "/guile", ["guile.cpp" ], SHLIBPREFIX="")


