#-*- mode: python -*-
Import('dest_dir','listinc')

local_listinc=[
      GetLaunchDir(),
      '../../../',
      '/usr/local/include',
      '/usr/include/',
      '/usr/local/include/libxml2',
      '/usr/include/libxml2',
      '.'
      ]

local_listinc.extend(listinc)

env = Environment(CPPPATH=local_listinc)

conf = Configure(env, config_h="config.h")


if conf.CheckLib("magic") and conf.CheckHeader("magic.h"):
    conf.Define('MAGIC', 1)
else:
    print "Cannot find the library magic"
    raise


env = conf.Finish()

env.SharedLibrary(GetLaunchDir() + "/" + dest_dir + "/mime_magic", ["mime_magic.cpp" ], SHLIBPREFIX="")

Command(GetLaunchDir() + "/" + dest_dir + "/README","README", Copy("$TARGET", "$SOURCE"))
